### ISSUE TITLE
请教一下如何发送Gif 图片

### ISSUE THREAD

**Issue by zhuweideng** [ElfSundae/NIM_iOS_UIKit#3]
请教一下如何发送Gif 图片

**Comment by ElfSundae** [comment]
抱歉我没用过这个库，没法回答你。
不知道你问的是 图片消息发送失败 还是 消息发送成功了但不显示动态 GIF ？
建议你看看它内部是怎么封装消息的，是不是图片被压缩成 JPG 或 PNG 了。如果内置不支持 GIF 图片可以自定义消息类型，Demo 里有自定义消息的示例。
